### ISSUE TITLE
Auth/Register storage recommendations

### ISSUE THREAD

**Issue by incidrthreat** [golang-friends/slack-clone#5]
Looking for suggestions here.  I am most familiar with Mongodb, Redis, and MySQL.

**Comment by kkweon** [comment]
I use mongodb as it's pretty much free for side projects (https://www.mongodb.com/pricing).
Since we're using protobuf, it should be easy to avoid tight coupling, so i think we just choose (mongodb) and move forward.

For example, what's more important is the interface API, imo.

```go
type AuthRepository interface {
  StoreUser(user pb.User) error
  LookupUser(userId string) (*pb.User, error)
  // ...
}

type MongoDbAuthRepository struct {
 // ...
}
type MySqlDbAuthRepository struct {
 // ...
}
```

And then used in service

```go
// we can swap authRepo whenever we can
func NewAuthService(authRepository AuthRepository) *AuthService {
  // ...
}
```

**Comment by itzmanish** [comment]
Better go with mongodb

**Comment by incidrthreat** [comment]
> 
> 
> Better go with mongodb

Thanks, we ended up going with mongodb.  Closing "issue".
